"""add phone_number

Revision ID: 59626320fb3f
Revises: 0cdc5f0e4772
Create Date: 2022-08-20 13:30:01.563547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59626320fb3f'
down_revision = '0cdc5f0e4772'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
